### ISSUE TITLE
Is it possible to use python3 in virtstrap environment?

### ISSUE THREAD

**Issue by arve0** [ravenac95/virtstrap#4]
I love virtstrap, but I'm unable to find out if its possible to bootstrap a environment with python 3. Is this possible?

**Comment by ravenac95** [comment]
@arve0 You made my day! Not many people other than me and my company use virtstrap. I have not been able to do much in the way of testing this for python3. I'm not sure if it would work yet. I will keep you posted on details there as I have them.

**Comment by arve0** [comment]
Sweet, thanks:-)
